Repository devfile/devfile-web, pull requests merged in 2022-11, with the labels that each got.

#55 Updated the api workflow to better reflect versioning
  python/.gitignore
  python/README.md
  python/src/api_workflow/api_workflow.py
  python/testing_directory/backup/config/stable-version.txt
  python/testing_directory/backup/config/version.ts
  python/testing_directory/backup/config/versions.txt
  python/testing_directory/backup/devfile_schemas/2.0.0.json
  python/testing_directory/backup/devfile_schemas/2.1.0.json
  python/testing_directory/backup/devfile_schemas/2.2.0-alpha.json
  python/testing_directory/backup/docs/2.0.0/test.md
  python/testing_directory/backup/docs/2.1.0/test.md
  python/testing_directory/backup/docs/2.2.0-alpha/test.md
  python/testing_directory/backup/navigation/2.0.0.yaml
  python/testing_directory/backup/navigation/2.1.0.yaml
  python/testing_directory/backup/navigation/2.2.0-alpha.yaml
  python/tests/test_api_workflow.py
Labels: approved, lgtm

#54 RHDEVDOCS-2562 adding starterProjects
  libs/docs/src/docs/2.0.0/defining-starter-projects.md
  libs/docs/src/docs/2.1.0/defining-starter-projects.md
  libs/docs/src/docs/2.2.0/defining-starter-projects.md
  libs/docs/src/navigation/2.0.0.yaml
  libs/docs/src/navigation/2.1.0.yaml
  libs/docs/src/navigation/2.2.0.yaml
Labels: lgtm

#58 Revisions to `build_viewer.sh`
  scripts/build_viewer.sh
Labels: approved, lgtm

#57 Fixed deploy-landing-page action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-landing-page.yml
Labels: approved, lgtm

#26 Add clarification within docs
  libs/docs/src/docs/2.2.0/adding-a-container-component.md
Labels: approved

#60 Adds integrate with editors page
  .gitignore
  apps/landing-page/markdoc/tags.tsx
  libs/core/src/components/index.ts
  libs/core/src/components/video/video.tsx
  libs/core/src/icons/devfile-icon.tsx
  libs/docs/src/docs/no-version/integrate-with-editors.md
  libs/docs/src/navigation/no-version.yaml
Labels: approved, lgtm

#39 Devfile Template Guide
  libs/docs/src/docs/2.2.0/create-devfiles-with-templates.md
  libs/docs/src/docs/2.2.1-alpha/create-devfiles-with-templates.md
  libs/docs/src/navigation/2.2.0.yaml
  libs/docs/src/navigation/2.2.1-alpha.yaml
Labels: lgtm
